load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "ex1",
  srcs = ["ex1.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "ex2",
  srcs = ["ex2.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "ex3",
  srcs = ["ex3.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "ex4",
  srcs = ["ex4.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
