load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "exercise_1",
  srcs = ["ex1.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_2",
  srcs = ["ex2.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_3",
  srcs = ["ex3.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_4",
  srcs = ["ex4.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
