load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "map_test",
    srcs = ["map.cpp"],
    deps = [
        "//modern_cpp_examples/map/utils:bucket",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
