load("@rules_cc//cc:defs.bzl",  "cc_test")


cc_test(
  name = "all",
  srcs = glob(["exercise_*.cpp"]),
  deps = [
    "//modern_cpp_examples/map/utils:bucket",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_1",
  srcs = ["exercise_1.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_2",
  srcs = ["exercise_2.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_3",
  srcs = ["exercise_3.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_4",
  srcs = ["exercise_4.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_5",
  srcs = ["exercise_5.cpp"],
  deps = [
    "//modern_cpp_examples/map/utils:bucket",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_6",
  srcs = ["exercise_6.cpp"],
  deps = [
    "//modern_cpp_examples/map/utils:bucket",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_7",
  srcs = ["exercise_7.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_8",
  srcs = ["exercise_8.cpp"],
  deps = [
    "//modern_cpp_examples/map/utils:bucket",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_9",
  srcs = ["exercise_9.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_10",
  srcs = ["exercise_10.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_11",
  srcs = ["exercise_11.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_12",
  srcs = ["exercise_12.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_13",
  srcs = ["exercise_13.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_14",
  srcs = ["exercise_14.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
