load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
  name = "exercise_1",
  srcs = ["exercise_1.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_2",
  srcs = ["exercise_2.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "exercise_3",
  srcs = ["exercise_3.cpp"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)
